# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: moder_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'moder_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13moder_service.proto\x12\x05moder\"\x1c\n\x0cModerRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\rModerResponse\x12\x0e\n\x06isTrue\x18\x02 \x01(\x08\x32K\n\x0cModerService\x12;\n\x0cPredictModer\x12\x13.moder.ModerRequest\x1a\x14.moder.ModerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'moder_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODERREQUEST']._serialized_start=30
  _globals['_MODERREQUEST']._serialized_end=58
  _globals['_MODERRESPONSE']._serialized_start=60
  _globals['_MODERRESPONSE']._serialized_end=91
  _globals['_MODERSERVICE']._serialized_start=93
  _globals['_MODERSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
